### ISSUE TITLE
slow and jaggy sound rendering

### ISSUE THREAD

**Issue by farvardin** [bintracker/bintracker#3]
When using default settings, mame opens in a big window, using filters, altering the whole experience of using bintracker because the sound renders badly, with some slowdown and jaggy sound.

I've noticed lowering the mame window makes the sound better. 

I've also put those options in emulators.scm:

>  "-nomax" "-video" "opengl" "-nofilter"

it seems to help a bit.

**Comment by utz82** [comment]
This is down to either MAME being memory hungry, or possibly bad ALSA/pulseaudio configuration. Do you have Pulseaudio installed? If so, I'd love to recommend you get rid of it, but that's quite tricky nowadays. Anyway, a quick fix to all sound problems should be adding `-video none` or possibly `-autoframeskip` in `emulators.scm`. I will add a note regarding that in the FAQ.

I actually want to be able to (optionally) run MAME without opening a render window at all but that might require some hacks in MAME itself, which I don't quite feel up to yet.

**Comment by farvardin** [comment]
I've tried with "-video none" but it complained it was for benchmarking, and moreover the mame window was transparent and looked like it crashed, so it wasn't better. I hadn't tried "-autoframeskips" because I feared it might degrade the sound. Anyway, with "-nofilter" and "-nomax" it was much better!

I tried so hard to get rid of pulseaudio, but it's quite complicated, I'm using this computer for MAO, with jackd, and I have less issue by letting pulseaudio on the system (for example I had problem to have sound in firefox or vlc when pulseaudio was disabled)

**Comment by utz82** [comment]
Ok, that's clearly a +1 for needing to fork MAME. I mean ultimately having video emulation is a nice bonus, but otherwise completely unnecessary for Bintracker.

Yes,  that's the biggest issue, not having pulseaudio pretty much means compiling your own firefox these days (I think Debian-based distros still ship a pa-free version but obviously you won't get that if you just have pa disabled).

Anyway thanks for the tip with -nofiler and -nomax, I'll add these to the docs. I'll close this issue afterwards but feel free to reopen if there are any new insights.
