### ISSUE TITLE
How far can this be taken?

### ISSUE THREAD

**Issue by bryc** [bintracker/bintracker#7]
This project seems quite ambitious (I am reminded of [SOULlang](https://github.com/soul-lang/SOUL)), supporting as many sound chips as possible, as well as being 'hackable'. Definitely got my interest. So I'm wondering how far it can be taken. Also, obviously it is still in the early stages so I don't expect everything to work already.

Lets say I wanted to use specific existing sound drivers (and was willing to do the work necessary):

1. Atari ST Chipmon2 sound driver and editor
2. Atari ST Magic Synth v2.5 sound driver and editor
3. ZX Spectrum Sound Tracker (STC) sound driver and editor
3. C64 Rob Hubbard's sound driver and editor
4. NES Super Mario Bros. sound driver and editor

Or create new sound drivers for systems without trackers, such as the Virtual Boy. Or some exotic Amiga sound drivers such as Art of Noise, Sonic Arranger and Musicline Editor.

Or create an environment with 'mix and match' capabilities, such as SID+OPL2 or even more exotic combinations such as Rob Hubbard driver + Siduzzit driver in a 2SID setup.

Or perhaps an MML editor/compiler, or custom DSP code for new sound engines ('fakebit')? Such as designing a PCEngine-like wavescanning synth for one channel and a custom 2-op FM with an additive/waveshaping oscillator for another.

**** 

What are some reasonable expectations for what might be achievable with this framework when it's stable?

Cheers, and best of luck on it!

**Comment by utz82** [comment]
Hi, pretty much all of this is within the scope of this project, though varying amounts of work are needed to get there.

Generally speaking, for each of these drivers you'd need to write a MDEF config, and translate the player code to Schemta (Bintracker's assembler) syntax. The main blocking issue is that the internal compiler (MDAL) is missing some crucial features, so depending on how the data for these drivers is structured it may or may not be possible at this point.

Additionally, the following things are missing right now:

1. & 2., require support for 68k. I recently realized that the design of Bintracker's assembler is a poor match for CPUs with many addressing modes, so I need to do some thinking on how to improve the situation first. More importantly though, Atari ST emulation in MAME is broken so either that needs to be fixed, or we'll need to find another emulator that can be scripted somehow. Haven't looked into it but I definitely want to have support for the ST.

3. just needs support for Spectrum 128K. That should be trivial, just haven't gotten around to it yet. It'll probably be one of the first things I'll do when I start to work on the project again (just moved to a new country a few days ago, so still need a week or two to sort out some things). If you want to try yourself it basically just needs an entry in [config/systems.scm](https://github.com/bintracker/bintracker/blob/master/config/systems.scm). As mentioned above, I'm not sure MDAL can handle STC's binary format yet, though.

4. 65xx support is done, so just need to add support for C64. Iirc MAME uses reSID so SID emulation should be fine, but eventually I want to get VICE working with Bintracker, so some of the more exotic things (2SID, SFX Expander) become available, too.

5. Haven't looked into NES much at all, but should be doable.

One additional thing to consider is copyright. I don't want to distribute drivers that aren't licensed under some liberal OSS license (because [reasons](https://bintracker.org/documentation/contributing.html#chose-a-license-for-my-contributions) ). I won't stop anyone from distributing them unofficially though ;)

A driver for Virtual Boy would definitely be something I'd want to see in Bintracker, that kind of thing is the main motivation for the project.

Multi-chip/driver setups are on the to-do list, but will take some more time to get done. Don't think I'll get around to that for the beta release.

Basic MML support is already implemented, so it's basically a question of expanding the parser and making conversion more intelligent.

Custom DSP code would in theory be possible, though it's not my main focus. The main thing here is that currently Bintracker is rather closely married to MAME as far as emulation/sound output is concerned, but changing that is quite high on the priority list (mostly because I want to have VIC20 support :D).

Anyway, would be more than happy to have you aboard for these things! (you had me at Virtual boy :D)

**Comment by utz82** [comment]
Hi, pretty much all of this is within the scope of this project, though varying amounts of work are needed to get there.

Generally speaking, for each of these drivers you'd need to write a MDEF config, and translate the player code to Schemta (Bintracker's assembler) syntax. The main blocking issue is that the internal compiler (MDAL) is missing some crucial features, so depending on how the data for these drivers is structured it may or may not be possible at this point.

Additionally, the following things are missing right now:

1. & 2., require support for 68k. I recently realized that the design of Bintracker's assembler is a poor match for CPUs with many addressing modes, so I need to do some thinking on how to improve the situation first. More importantly though, Atari ST emulation in MAME is broken so either that needs to be fixed, or we'll need to find another emulator that can be scripted somehow. Haven't looked into it but I definitely want to have support for the ST.

3. just needs support for Spectrum 128K. That should be trivial, just haven't gotten around to it yet. It'll probably be one of the first things I'll do when I start to work on the project again (just moved to a new country a few days ago, so still need a week or two to sort out some things). If you want to try yourself it basically just needs an entry in [config/systems.scm](https://github.com/bintracker/bintracker/blob/master/config/systems.scm). As mentioned above, I'm not sure MDAL can handle STC's binary format yet, though.

4. 65xx support is done, so just need to add support for C64. Iirc MAME uses reSID so SID emulation should be fine, but eventually I want to get VICE working with Bintracker, so some of the more exotic things (2SID, SFX Expander) become available, too.

5. Haven't looked into NES much at all, but should be doable.

One additional thing to consider is copyright. I don't want to distribute drivers that aren't licensed under some liberal OSS license (because [reasons](https://bintracker.org/documentation/contributing.html#chose-a-license-for-my-contributions) ). I won't stop anyone from distributing them unofficially though ;)

A driver for Virtual Boy would definitely be something I'd want to see in Bintracker, that kind of thing is the main motivation for the project.

Multi-chip/driver setups are on the to-do list, but will take some more time to get done. Don't think I'll get around to that for the beta release.

Basic MML support is already implemented, so it's basically a question of expanding the parser and making conversion more intelligent.

Custom DSP code would in theory be possible, though it's not my main focus. The main thing here is that currently Bintracker is rather closely married to MAME as far as emulation/sound output is concerned, but changing that is quite high on the priority list (mostly because I want to have VIC20 support :D).

Anyway, would be more than happy to have you aboard for these things! (you had me at Virtual boy :D)
